# Generated by Django 4.2.29 on 2026-03-16 11:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("bookings", "0002_booking_address_booking_price"),
    ]

    operations = [
        migrations.CreateModel(
            name="EscrowPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "stripe_payment_intent_id",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        verbose_name="Stripe PaymentIntent ID",
                    ),
                ),
                (
                    "amount",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Amount"
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        default="eur", max_length=3, verbose_name="Currency"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("HELD", "Held"),
                            ("RELEASED", "Released"),
                            ("REFUNDED", "Refunded"),
                            ("DISPUTED", "Disputed"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="Status",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        help_text="card, paypal, mbway",
                        max_length=20,
                        verbose_name="Payment Method",
                    ),
                ),
                (
                    "paid_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="Paid At"),
                ),
                (
                    "released_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Released At"
                    ),
                ),
                (
                    "refunded_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Refunded At"
                    ),
                ),
                (
                    "booking",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payment",
                        to="bookings.booking",
                        verbose_name="Booking",
                    ),
                ),
            ],
            options={
                "verbose_name": "Escrow Payment",
                "verbose_name_plural": "Escrow Payments",
                "ordering": ["-created_at"],
            },
        ),
    ]
