# Generated by Django 4.2.27 on 2026-02-19 00:01

from django.db import migrations, models

# GIS fallback — use TextField when GDAL / GIS libs are unavailable
try:
    from django.contrib.gis.db.models.fields import PointField as _PointField
except (ImportError, OSError, Exception):
    class _PointField(models.TextField):
        description = "Mock PointField (GDAL not available)"
        def __init__(self, *args, **kwargs):
            kwargs.pop('srid', None)
            kwargs.pop('geography', None)
            super().__init__(*args, **kwargs)


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='location',
            field=_PointField(blank=True, geography=True, null=True, srid=4326, verbose_name='Location'),
        ),
    ]
